### ISSUE TITLE
Save code to new file doesn't work

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/cody-vs#147]
**Customer Information**

Client : VS 2022 Community Edition

Client Version: 0.1.1

IDE Version: 17.12.1

Client OS: Windows 11

Slack Discussion: https://sourcegraph.slack.com/archives/C073U3KE5DK/p1732208831585229

Summary of Issue

When Cody sends a Code block and the user clicks the third button labeled "Save Code to New File," no action occurs.

**Steps to Reproduce**

(If we cannot reproduce the issue, explain why and describe the steps taken to attempt reproduction)

Screenshot / Video

![image](https://github.com/user-attachments/assets/1a59fa6e-be09-40af-a1d9-71d4efb75f1e)

Relevant Logs
```
07:47:35.453: [ProcessId:5600] [ThreadId:67] Error [OnErrorReceived] Uncaught exception: _ResponseError: Unable to find method 'window/showSaveDialog/0' on {no object} for the following reasons: An argument was not supplied for a required parameter.
07:47:35.453: [ProcessId:5600] [ThreadId:67] Error [OnErrorReceived]     at handleResponse (c:\users\justindorfman\appdata\local\microsoft\visualstudio\17.0_b86b6190\extensions\node_modules\.pnpm\vscode-jsonrpc@8.2.0\node_modules\vscode-jsonrpc\lib\common\connection.js:565:48)
07:47:35.453: [ProcessId:5600] [ThreadId:67] Error [OnErrorReceived]     at handleMessage (c:\users\justindorfman\appdata\local\microsoft\visualstudio\17.0_b86b6190\extensions\node_modules\.pnpm\vscode-jsonrpc@8.2.0\node_modules\vscode-jsonrpc\lib\common\connection.js:345:13)
07:47:35.459: [ProcessId:5600] [ThreadId:67] Error [OnErrorReceived]     at processMessageQueue (c:\users\justindorfman\appdata\local\microsoft\visualstudio\17.0_b86b6190\extensions\node_modules\.pnpm\vscode-jsonrpc@8.2.0\node_modules\vscode-jsonrpc\lib\common\connection.js:362:17)
07:47:35.459: [ProcessId:5600] [ThreadId:67] Error [OnErrorReceived]     at Immediate.<anonymous> (c:\users\justindorfman\appdata\local\microsoft\visualstudio\17.0_b86b6190\extensions\node_modules\.pnpm\vscode-jsonrpc@8.2.0\node_modules\vscode-jsonrpc\lib\common\connection.js:334:13)
07:47:35.459: [ProcessId:5600] [ThreadId:67] Error [OnErrorReceived]     at process.processImmediate (node:internal/timers:478:21)
07:47:35.459: [ProcessId:5600] [ThreadId:67] Error [OnErrorReceived]     at process.topLevelDomainCallback (node:domain:160:15)
07:47:35.459: [ProcessId:5600] [ThreadId:67] Error [OnErrorReceived]     at process.callbackTrampoline (node:internal/async_hooks:128:24) {
07:47:35.459: [ProcessId:5600] [ThreadId:67] Error [OnErrorReceived]   code: -32602,
07:47:35.459: [ProcessId:5600] [ThreadId:67] Error [OnErrorReceived]   data: undefined
07:47:35.459: [ProcessId:5600] [ThreadId:67] Error [OnErrorReceived] }
07:47:40.645: [ProcessId:5600] [ThreadId:67] Error [OnErrorReceived] graphql.fetch.RecordTelemetryEvents - 198.6309ms
```
Repo Configuration

n/a

Related Issues / Documentation

n/a

Troubleshooting Steps Completed So Far

n/a

Impact to Customer

Can't use a feature

Expected Actions / Questions for Engineering

**Comment by tomaszgolebiowski** [comment]
This is fixed in version 0.1.2. We have hidden the unsupported buttons.
